---
- name: Enable epel-release.
  package:
    name: epel-release
    state: present
  tags:
    - install-packages-rh

- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present
  tags:
    - install-packages-rh

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis
  tags:
    - install-redis-rh

