---
- name: Install nginx on server
  package:
    name: nginx
    state: present
    update_cache: true
  tags:
    - install-nginx

- name: Remove default nginx config file.
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart nginx
  when: ansible_os_family == 'Debian'
  tags:
    - install-nginx-deb
