jobs:
  include:
    - stage: Build and push image
      if: branch =~ ^(develop|master)$ and type = push
      before_script: 
        - pip install --user awscli
      script:
        - echo "this is fake linter in master branch" 

    - stage: Deploy dev
      if: branch = develop and type = push
      install:
        - sudo pip install ansible botocore boto3
      before_script:
        - cd deploy/ansible
      script:
        - echo "this is fake deploy to dev from master branch"
