---
__php_default_version_debian: "7.0"

__php_packages:
  - php{{ php_default_version_debian }}-common
  - php{{ php_default_version_debian }}-cli
  - php{{ php_default_version_debian }}-dev
  - php{{ php_default_version_debian }}-fpm
  - libpcre3-dev

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/{{ php_default_version_debian }}/fpm
  - /etc/php/{{ php_default_version_debian }}/cli

__php_extension_conf_paths:
  - /etc/php/{{ php_default_version_debian }}/fpm/conf.d
  - /etc/php/{{ php_default_version_debian }}/cli/conf.d

__php_fpm_daemon: php{{ php_default_version_debian }}-fpm
__php_fpm_conf_path: "/etc/php/{{ php_default_version_debian }}/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__fpm_listner: "/var/run/php/php-fpm.sock"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data

__php_mods:
  - php{{ php_default_version_debian }}-opcache
  - php{{ php_default_version_debian }}-xml
  - php{{ php_default_version_debian }}-gd

