---
__php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm

__php_conf_paths:
  - /etc

__php_extension_conf_paths:
  - /etc/php.d

__php_fpm_daemon: php-fpm
__php_fpm_conf_path: "/etc/fpm"
__php_fpm_pool_conf_path: "/etc/php-fpm.d/www.conf"

__fpm_listner: "/var/run/php-fpm/php-fpm.sock"

__php_fpm_pool_user: nginx
__php_fpm_pool_group: nginx

__php_mods:
  - php-gd
  - php-ldap
  - php-mbstring
  - php-pear
  - php-xml

