---
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false
  tags:
    - mysql-configure


- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled=true"
  register: mysql_service_configuration
  tags:
    - mysql-configure
